steps:
- name: 'ubuntu'
  args: ['bash', './myscript.bash']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ianatest-164415/config-test', '.']
images: ['gcr.io/ianatest-164415/config-test']
